### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbasedevopschallenge#3]
Kafka Message 1
```
ERROR [main:o.a.z.s.q.QuorumPeerMain@104] - Unable to access datadir, exiting abnormally
org.apache.zookeeper.server.persistence.FileTxnSnapLog$LogDirContentCheckException: Log directory has snapshot files. Check if dataLogDir and dataDir configuration is correct.
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.checkLogDir(FileTxnSnapLog.java:188)
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.<init>(FileTxnSnapLog.java:165)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:178)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:137)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:91)
Unable to access datadir, exiting abnormally
2022-06-01 19:14:48,922 [myid:1] - INFO  [main:o.a.z.a.ZKAuditProvider@42] - ZooKeeper audit is disabled.
2022-06-01 19:14:48,923 [myid:1] - ERROR [main:o.a.z.u.ServiceUtils@42] - Exiting JVM with code 3
```

**Comment by bio-boris** [comment]
Mongo Error Message 2
```
I ACCESS [main] Error reading file /data/db/keyfile: No such file or directory
```

**Comment by bio-boris** [comment]
Mongo Error Message 3
```
2022-06-23T16:05:01.625+0000 I ACCESS [main] permissions on /data/db/keyfile are too open
```

**Comment by bio-boris** [comment]
Question 4: 

How do you ssh into a machine with these credentials?

```
Username: example_user
Password: password123
URL: ssh.kbase.com
```

**Comment by bio-boris** [comment]
Question 5:
How do you clear out a directory on a machine using a docker container?

**Comment by bio-boris** [comment]
Question 6:
How do you add a file into a directory in Kubernetes?
